version: 1
update_configs:
  - package_manager: java:maven
    directory: /
    update_schedule: weekly
    default_reviewers:
      - jglick
    ignored_updates:
      - match:
          dependency_name: com.google.guava:guava
      - match:
          dependency_name: com.google.inject.extensions:guice-assistedinject
